.TH NEWALIASES 8
.SH NEWALIASES
newaliases \- update /etc/aliases database
.SH SYNOPSIS
.B newaliases
.SH "DESCRIPTION"
This is a simple shell script calling
.B /usr/lib/sendmail
with the
.B -bi
option. It is provided for compatibility with the sendmail program.
.P
In this case it absolute does nothing since sSMTP does not support
/etc/aliases and is just there to avoid programs returning errormessages.
.SH AUTHOR
This manual page was written by Christoph Lameter <clameter@debian.org>,
for the Debian GNU/Linux system.
